namespace FourInARowBattle;

public enum LobbyManagerErrorEnum
{
    NONE,

    PLAYER_ALREADY_EXISTS,
    PLAYER_DOES_NOT_EXIST,

    LOBBY_ALREADY_EXISTS,
    LOBBY_DOES_NOT_EXIST,

    PLAYER_ALREADY_IN_LOBBY,
    PLAYER_NOT_IN_LOBBY,

    LOBBY_IS_FULL,

    PLAYER_ALREADY_IN_THAT_LOBBY,

    REQUEST_ALREADY_EXISTS,
    REQUEST_DOES_NOT_EXIST,

    NO_OTHER_PLAYER,
    
    MID_GAME,


}